[workspace]
members = ["crates/*", "docs"]
default-members = ["crates/*", "docs"]
resolver = "2"

[workspace.dependencies]
cargo_metadata = "0.15"
clap = "4"
derive_more = "0.99"
doc-comment = "0.3"
insta = "1"
markdown = "1.0.0-alpha.7"
similar-asserts = "1"
rstest = "0.17"
semver = "1"
serde = "1"
serde_json = "1"
thiserror = "1"
typed-builder = "0.14"

# Internal crates
monochange = { path = "./crates/monochange", version = "0.0.0" }
monochange_core = { path = "./crates/monochange_core", version = "0.0.0" }
monochange_cargo = { path = "./crates/monochange_cargo", version = "0.0.0" }
monochange_npm = { path = "./crates/monochange_npm", version = "0.0.0" }

[workspace.package]
version = "0.0.0"
homepage = "https://github.com/ifiokjr/monochange"
repository = "https://github.com/ifiokjr/monochange"
authors = ["Ifiok Jr. <ifiokotung@gmail.com>"]
edition = "2021"
license = "Unlicense"
rust-version = "1.68.0"
categories = ["development-tools"]
readme = "readme.md"
include = ["src/**/*.rs", "Cargo.toml", "readme.md"]
