[defaults]
parent_bump = "patch"
include_private = false
warn_on_group_mismatch = true
package_type = "cargo"

[package.monochange]
path = "crates/monochange"
changelog = "crates/monochange/changelog.md"

[package.monochange_core]
path = "crates/monochange_core"
changelog = "crates/monochange_core/changelog.md"

[package.monochange_cargo]
path = "crates/monochange_cargo"
changelog = "crates/monochange_cargo/changelog.md"

[package.monochange_npm]
path = "crates/monochange_npm"
changelog = "crates/monochange_npm/changelog.md"

[package.monochange_config]
path = "crates/monochange_config"
changelog = "crates/monochange_config/changelog.md"

[package.monochange_deno]
path = "crates/monochange_deno"
changelog = "crates/monochange_deno/changelog.md"

[package.monochange_dart]
path = "crates/monochange_dart"
changelog = "crates/monochange_dart/changelog.md"

[package.monochange_graph]
path = "crates/monochange_graph"
changelog = "crates/monochange_graph/changelog.md"

[package.monochange_semver]
path = "crates/monochange_semver"
changelog = "crates/monochange_semver/changelog.md"

[group.main]
packages = [
	"monochange",
	"monochange_core",
	"monochange_cargo",
	"monochange_npm",
	"monochange_config",
	"monochange_deno",
	"monochange_dart",
	"monochange_graph",
	"monochange_semver",
]
tag = true
release = true
version_format = "primary"

[ecosystems.cargo]
enabled = true

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"
