[defaults]
parent_bump = "patch"
include_private = false
warn_on_group_mismatch = true
package_type = "cargo"
changelog = "{path}/changelog.md"

[package.monochange]
path = "crates/monochange"

[package.monochange_core]
path = "crates/monochange_core"

[package.monochange_cargo]
path = "crates/monochange_cargo"

[package.monochange_npm]
path = "crates/monochange_npm"

[package.monochange_config]
path = "crates/monochange_config"

[package.monochange_deno]
path = "crates/monochange_deno"

[package.monochange_dart]
path = "crates/monochange_dart"

[package.monochange_graph]
path = "crates/monochange_graph"

[package.monochange_semver]
path = "crates/monochange_semver"

[group.main]
packages = [
	"monochange",
	"monochange_core",
	"monochange_cargo",
	"monochange_npm",
	"monochange_config",
	"monochange_deno",
	"monochange_dart",
	"monochange_graph",
	"monochange_semver",
]
changelog = "changelog.md"
tag = true
release = true
version_format = "primary"

[ecosystems.cargo]
enabled = true

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"
