[package]
name = "monochange_core"
version = { workspace = true }
categories = { workspace = true }
documentation = "https://docs.rs/monochange_core"
edition = { workspace = true }
include = { workspace = true }
keywords = ["cli", "changelog", "releases", "versioning", "monorepo"]
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Manage versions and releases for you multiplatform, multilanguage monorepo"

[dependencies]
cargo_metadata = { workspace = true }
doc-comment = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
