[package]
name = "monochange_core"
version = "0.0.0"
edition = "2021"
documentation = "https://docs.rs/monochange_core"
categories = ["development-tools"]
include = ["src/**/*.rs", "Cargo.toml", "readme.md"]
keywords = ["cli", "changelog", "releases", "versioning", "monorepo", ]
repository = "https://github.com/ifiokjr/monochange"
description = "Manage versions and releases for you multiplatform, multilanguage monorepo"
rust-version = "1.67.0"

[dependencies]
