[package]
name = "monochange"
version = "0.0.0"
edition = "2021"
documentation = "https://docs.rs/monochange"
categories = ["development-tools", "command-line-utilities"]
include = ["src/**/*.rs", "Cargo.toml", "readme.md"]
keywords = ["cli", "changelog", "releases", "versioning", "monorepo", ]
repository = "https://github.com/ifiokjr/monochange"
description = "Manage versions and releases for you multiplatform, multilanguage monorepo"
rust-version = "1.67.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monochange_core = { workspace = true }