[package]
name = "monochange_npm"
version = { workspace = true }
categories = { workspace = true }
documentation = "https://docs.rs/monochange_core"
edition = { workspace = true }
include = { workspace = true }
keywords = []
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Manage versions and releases for you multiplatform, multilanguage monorepo"

[dependencies]
doc-comment = { workspace = true }
monochange_core = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
rstest = { workspace = true }
similar-asserts = { workspace = true }
