name: "ci"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: lint clippy
        run: lint:clippy
        shell: devenv shell -- bash -e {0}

      - name: lint formatting
        run: lint:format
        shell: devenv shell -- bash -e {0}

      - name: cargo deny
        run: deny:check
        shell: devenv shell -- bash -e {0}

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: run tests
        run: test:all
        shell: devenv shell -- bash -e {0}

  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: build:all
        shell: devenv shell -- bash -e {0}

      - name: build book
        run: build:book
        shell: devenv shell -- bash -e {0}
